### ISSUE TITLE
Add tutorial game by Adam Cadre

### ISSUE THREAD

**Issue by dalb8** [onyxbits/TextFiction#16]
He has written a game that serves as a intro to IF. The z-code file is available via this URL: http://adamcadre.ac/if.html.

The current recommended player on that website is zmpp4droid which hasn't been updated in a long while so I take it that he doesn't know about TextFiction: "(The Windows player is the only one I can actually vouch for, because that's what I use. If you have different links to suggest for the other systems, or for systems that should be added to this list, let me know.) "

**Comment by onyxbits** [comment]
Tried Adams tutorial. I don't think it is suitable for TextFiction (mentions several things you won't see in the app, e.g. the command prompt).

**Comment by dalb8** [comment]
Oops. Also I can't get out of key mode when it comes time to type the first command: I can only get one character in each bubble.

 BTW I tried Photopia and that produces 'corrupt game file' after the first prompt.


-------- Message d'origine --------
De : onyxbits <notifications@github.com>
Envoyé: 4 février 2016 02:44:06 UTC+00:00
À : onyxbits/TextFiction <TextFiction@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [TextFiction] Add tutorial game by Adam Cadre (#16)

Tried Adams tutorial. I don't think it is suitable for TextFiction (mentions several things you won't see in the app, e.g. the command prompt).

---

**Comment by dalb8** [comment]
Sorry, what I meant to write in the first paragraph was that I cant type 'Open the gate.' because the 'O' is not accepted as valid. 'o' is but 'open the gate' isn't.


-------- Message d'origine --------
De : onyxbits <notifications@github.com>
Envoyé: 4 février 2016 02:44:06 UTC+00:00
À : onyxbits/TextFiction <TextFiction@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [TextFiction] Add tutorial game by Adam Cadre (#16)

Tried Adams tutorial. I don't think it is suitable for TextFiction (mentions several things you won't see in the app, e.g. the command prompt).

---
