### ISSUE TITLE
Action Bar Menu during game play isn't there to Flip View, "wait for key mode"

### ISSUE THREAD

**Issue by WakeRealityDev** [onyxbits/TextFiction#20]
Hello, and thank you for the great software.

I noticed that the screen shots you have on Google Play differ from what I get when I run the app on a device. I've tried both 7" tablet and 10" tablet.  Also note that much-older Android devices have a physical "menu button" - but that has largely been obsoleted by Google design changes on newer devices.  I tested Text Fiction with an Android 7 and Android 4.2 tablet and had the same problem on both.

An example story of this is Anchorhead (anchor.z8) and the opening screen.  There is a **quote "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown. -- H.P. Lovecraft"** above the story title (or on Flip View in Text Fiction's rendering).

The issue is that the opening screen story title is on the Flip View side and in keystroke ("wait for key mode") input mode.  I can't find any way to tell Text Fiction to Flip View to view the story title text.  The menus are absent at the top of the screen during story play (looks like commit c9ff779e0ccdbcad0f94b29040e50bad349f0d25 and commit 205c7794d525af99f4a85cb7c089cefd8f97f029 were done after the original Google Play screen shots, removing menu?).  I didn't see any options in the settings to enable the action bar.

EDIT: The Handbook for Text Fiction even has a screen shot depicting the opening screen of Anchorhead:
![alt text](http://www.onyxbits.de/sites/default/files/illustration/138/screenshot.png "Text Fiction Anchorhead")

Perhaps I'm overlooking a UI convention, Is there some place to touch or long-touch to bring up the menu or otherwise Flip View?  Thank you.

**Comment by onyxbits** [comment]
Any of the keys in the button bar will continue the story.

**Comment by WakeRealityDev** [comment]
It isn't about what will continue the story. The issue is that a quote is never presented, there is missing information from the story.  In the case of Anchorhead, the opening quote:

"The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown. -- H.P. Lovecraft"
